#pragma once

#define BASED_CLASS_COPY_CONSTRUCTOR(c) c (const c& other)
#define BASED_CLASS_MOVE_CONSTRUCTOR(c) c (c&& other)
#define BASED_CLASS_COPY_ASSIGNMENT(c) c& operator= (const c& other)
#define BASED_CLASS_MOVE_ASSIGNMENT(c) c& operator= (c&& other)

#define BASED_CLASS_DECL_COPY(c, d) \
	BASED_CLASS_COPY_CONSTRUCTOR(c) = d; \
	BASED_CLASS_COPY_ASSIGNMENT(c) = d;
#define BASED_CLASS_DECL_MOVE(c, d) \
	BASED_CLASS_MOVE_CONSTRUCTOR(c) = d; \
	BASED_CLASS_MOVE_ASSIGNMENT(c) = d;
#define BASED_CLASS_NO_COPY(c) BASED_CLASS_DECL_COPY(c, delete)
#define BASED_CLASS_NO_MOVE(c) BASED_CLASS_DECL_MOVE(c, delete)
#define BASED_CLASS_DEFAULT_COPY(c) BASED_CLASS_DECL_COPY(c, default)
#define BASED_CLASS_DEFAULT_MOVE(c) BASED_CLASS_DECL_MOVE(c, default)
#define BASED_CLASS_NO_COPY_MOVE(c) \
	BASED_CLASS_NO_COPY(c); \
	BASED_CLASS_NO_MOVE(c);
#define BASED_CLASS_NO_COPY_DEFAULT_MOVE(c) \
	BASED_CLASS_NO_COPY(c); \
	BASED_CLASS_DEFAULT_MOVE(c);

#define BASED_CLASS_EQUALITY_OPERATOR(c) bool operator== (const c& other) const
#define BASED_CLASS_DECL_EQUALITY(c, d) BASED_CLASS_EQUALITY_OPERATOR(c) = d;
#define BASED_CLASS_DEFAULT_EQUALITY(c) BASED_CLASS_DECL_EQUALITY(c, default)
