#pragma once

#define BASED_CLASS_COPY_CONSTRUCTOR(c) c (const c&)
#define BASED_CLASS_MOVE_CONSTRUCTOR(c) c (c&&)
#define BASED_CLASS_COPY_ASSIGNMENT(c) c& operator= (const c&)
#define BASED_CLASS_MOVE_ASSIGNMENT(c) c& operator= (c&&)

#define BASED_CLASS_DECL_COPY(c, d) \
	BASED_CLASS_COPY_CONSTRUCTOR(c) = d; \
	BASED_CLASS_COPY_ASSIGNMENT(c) = d;
#define BASED_CLASS_DECL_MOVE(c, d) \
	BASED_CLASS_MOVE_CONSTRUCTOR(c) = d; \
	BASED_CLASS_MOVE_ASSIGNMENT(c) = d;
#define BASED_CLASS_NO_COPY(c) BASED_CLASS_DECL_COPY(c, delete)
#define BASED_CLASS_NO_MOVE(c) BASED_CLASS_DECL_MOVE(c, delete)
#define BASED_CLASS_DEFAULT_COPY(c) BASED_CLASS_DECL_COPY(c, default)
#define BASED_CLASS_DEFAULT_MOVE(c) BASED_CLASS_DECL_MOVE(c, default)
#define BASED_CLASS_NO_COPY_MOVE(c) \
	BASED_CLASS_NO_COPY(c); \
	BASED_CLASS_NO_MOVE(c);
#define BASED_CLASS_NO_COPY_DEFAULT_MOVE(c) \
	BASED_CLASS_NO_COPY(c); \
	BASED_CLASS_DEFAULT_MOVE(c);
